# Generated by Django 6.0.2 on 2026-02-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="ФИО")),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("developer", "Разработчик"),
                            ("designer", "Дизайнер"),
                            ("manager", "Менеджер"),
                            ("analyst", "Аналитик"),
                            ("tester", "Тестировщик"),
                        ],
                        max_length=50,
                        verbose_name="Должность",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "hire_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата найма"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
                "ordering": ["full_name"],
            },
        ),
    ]
